# Change these first
owner: unfurlyco # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Unfur.ly Landing Page
    url: https://unfur.ly/app/version
  - name: Unfur.ly App Login
    url: https://unfur.ly/app/login
  - name: Unfur.ly API
    url: https://unfur.ly/api/ui/info
  - name: Unfur.ly Redirector
    url: https://unfur.ly/version
  - name: Unfur.ly Free/Demo Tier Test
    url: https://unfur.ly/freetier
    expectedStatusCodes:
      - 302
      - 200
  - name: Unfur.ly Paid Tier Test
    url: https://unfur.ly/12345
    expectedStatusCodes:
      - 302
      - 200
  - name: Unfur.ly GeoFurl Test
    url: https://unfur.ly/BeastGames
    expectedStatusCodes:
      - 302
      - 200

status-website:
  theme: light
  # themeUrl: https://status.unfur.ly/unfurly-blue.css
  favicon: https://unfur.ly/app/favicon-96x96.png
  faviconSvg: https://unfur.ly/app/favicon.svg
  cname: status.unfur.ly
  logoUrl: https://unfur.ly/app/project/images/Unfurly_512.png
  name: " "
  introTitle: "**Status Page**"
  introMessage: |
    Welcome to the **_Unfur.ly_** status page. Here, you can find the current status of our link-shortening service and any ongoing incidents or maintenance events. 
    We strive to ensure maximum uptime and performance for our users. If you're experiencing issues, please [contact our support team](https://unfur.ly/support).
  navbar:
    - title: Home
      href: https://unfur.ly
    - title: Status
      href: /
    - title: Documentation
      href: https://unfur.ly/docs
    - title: Support
      href: https://unfur.ly/support
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
